# -*- coding: utf-8 -*-
"""YBI project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icv7oMjipepVULwrU2RckS9ezCC8Gci-

FINANCIAL MARKET NEWS - SENTIMENT ANALYSIS

Importing the library
"""

import pandas as pd

import numpy as np

df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Financial%20Market%20News.csv', encoding="ISO-8859-1")

df.head()

df.info()

df.shape

df.columns

' '.join(str(x) for x in df.iloc[1,2:27])

df.index

len(df.index)

n=[]
for row in range(0,len(df.index)):
  n.append(' '.join(str(x) for x in df.iloc[row,2:27]))

type(n)

n[0]

x= n

type(x)

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase = True, ngram_range=(1,1))

x=cv.fit_transform(x)

x.shape

y=df['Label']

y.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=2529)

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=200)

rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

confusion_matrix(y_test,y_pred)

print(classification_report(y_test,y_pred))

